### ISSUE TITLE
Add a way to start up an app with new empty volumes.

### ISSUE THREAD

**Issue by wallnerryan** [ClusterHQ/fli-docker#56]
If I have no existing snapshots or volumesets, i would like to bootstrap a compose app with empty fli volumes.

example

```
fli-docker -f fli-manifest -new
```
Where the manifest may look like
```
docker_app: cassandra.yml

flocker_hub:
    endpoint: https://data.flockerhub.clusterhq.com

volumes:
    - name: cassandra1
      snapshot:
      volumeset: cassandra-snapshots-01
    - name: cassandra2
      snapshot:
      volumeset: cassandra-snapshots-01
    - name: cassandra3
      snapshot:
      volumeset: cassandra-snapshots-01
```

Such that, empty volumes would be created  in volumeset `cassandra-snapshots-01` and if volumeset doesnt exist maybe use a `-create-vs` flag or something and the volumeset will get created locally first.
