### ISSUE TITLE
sync for multiple volumes from same volumeset inefficient 

### ISSUE THREAD

**Issue by wallnerryan** [ClusterHQ/fli-docker#58]
If you have a manifest like this

```

docker_app: cassandra.yml

flocker_hub:
    endpoint: https://data.flockerhub.clusterhq.com

volumes:
    - name: cassandra1
      snapshot: cassandra-snap-1
      volumeset: cassandra-vs
    - name: cassandra2
      snapshot: cassandra-snap-2
      volumeset: cassandra-vs
    - name: cassandra3
      snapshot: cassandra-snap-3
      volumeset: cassandra-vs
```

`fli-docker` will sync the volumeset for each snapshot or branch. This is because snapshots _may_ be from different volumesets. But in the case that they are, it still syncs every time. Maybe have a mechanism to hold what volumesets have been synced during the current `run` and skip if previously synced
